### ISSUE TITLE
don't like "hello"

### ISSUE THREAD

**Issue by nycdsaluke** [nycdsaluke/testcourse#20]
Supervisor: @nycdatafun 
Reviewer: @nycdatafun 
Coder:

comment: I don't like "hello" printed by [./try.py](https://github.com/nycdsaluke/testcourse/blob/master/try.py). Please make it better

**Comment by nycdatafun** [comment]
Supervisor: @nycdatafun
Reviewer: @nycdatafun
Coder:@LukeLinEx

Please change "hello" to "hi" in this file.
